spring:
  datasource:
    url: jdbc:mysql://localhost:3306/academia?useTimezone=true&serverTimezone=UTC
    username: root
    password: 1234Abreu@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
