server.port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: 1234
    #url: jdbc:mysql://localhost:3306/academia?useTimezone=true&serverTimezone=UTC
    #username: root
    #password: 1234Abreu@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  properties:
    hibernate.format_sql: true

  logging:
    level:
      org:
        hibernate:
          type: trace
